name: vyuh_feature_system
description: Provides the essential building blocks for a CMS-driven UI
version: 1.11.0
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_feature_system
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - feature
  - system

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  flutter_mobx: ^2.2.0+2
  json_annotation: ^4.8.1
  mobx: ^2.3.0+1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.3.0
  webview_flutter: ^4.4.3
  logger: ^2.0.2+1
  go_router: ^14.0.1
  flutter_sanity_portable_text: ^1.3.0
  vyuh_core: ^1.7.0
  vyuh_extension_content: ^1.4.0
  json_path: ^0.7.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
