name: feature_settings
description: Handles app-level settings that can be set on Sanity
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  json_annotation: ^4.8.1
  vyuh_core: ^1.32.2
  vyuh_feature_system: ^1.33.0
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
