name: vyuh_content_widget
description: A widget that can render content from a CMS, relying on the Vyuh ecosystem to provide the content.
version: 1.1.11
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_content_widget
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - content
  - widget
  - cms

environment:
  sdk: ^3.6.1
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0

  vyuh_core: ^1.40.1
  vyuh_extension_content: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
