name: vyuh_feature_developer
description: A Developer-focused feature that shows all the included features in a Vyuh-enabled App
version: 1.0.0-beta.2
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_feature_developer
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  flutter_sticky_header: ^0.6.5
  collection: ^1.18.0
  vyuh_core: ^1.0.0-beta.1
  vyuh_extension_content: ^1.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
