name: vyuh_cache
description: A generic caching package for Vyuh
version: 1.0.0
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_cache
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - cache
  - vyuh
  - system

environment:
  sdk: ^3.1.0

dependencies:
  crypto: ^3.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
