name: vyuh_widgetbook
description: Widgetbook implementation for previewing the various Content Items of Vyuh features
version: 1.2.1
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_widgetbook
issue_tracker: https://github.com/vyuh-tech/vyuh/issues
screenshots:
  - description: 'Vyuh Widgetbook showing content previews'
    path: doc/images/widgetbook.png

topics:
  - vyuh
  - widgetbook
  - content
  - preview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  vyuh_core: ^1.40.4
  vyuh_extension_content: ^1.21.1

  widgetbook: ^3.10.2

dev_dependencies:
  flutter_lints: ^5.0.0
