name: content_widget_demo
description: A demo to showcase the use of the VyuhContentWidget
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2

  vyuh_core: ^1.40.3
  vyuh_content_widget: ^1.1.11
  vyuh_extension_content: ^1.21.1
  sanity_client: ^1.7.5
  vyuh_plugin_content_provider_sanity: ^1.11.1
  vyuh_plugin_telemetry_provider_console: ^1.1.3

  feature_conference: ^1.0.0
  vyuh_feature_system: ^1.38.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
