name: content_widget_demo
resolution: workspace
description: A demo to showcase the use of the VyuhContentWidget
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0

  vyuh_core: ^1.51.0
  vyuh_content_widget: ^1.3.0
  vyuh_extension_content: ^1.30.0
  sanity_client: ^1.9.1
  vyuh_plugin_content_provider_sanity: ^1.14.1
  vyuh_plugin_telemetry_provider_console: ^1.3.0

  feature_conference: ^1.0.0
  vyuh_feature_system: ^1.43.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
