name: sanity_client_example
description: An example for using the sanity_client package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  sanity_client: ^1.7.6

dev_dependencies:
  lints: ^5.1.1
