name: vyuh_demo
resolution: workspace
description: A tech demo of the Vyuh Framework
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  go_router: ^16.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0

  # Sanity Integration
  sanity_client: ^1.9.0
  flutter_sanity_portable_text: ^1.8.0

  # Vyuh Framework
  vyuh_core: ^1.50.0
  vyuh_extension_content: ^1.30.0
  vyuh_feature_system: ^1.42.0
  vyuh_feature_developer: ^1.15.0
  vyuh_plugin_content_provider_sanity: ^1.14.0
  vyuh_feature_auth: ^1.22.0
  vyuh_feature_onboarding: ^1.8.0
  vyuh_plugin_telemetry_provider_console: ^1.3.0

  # Example Features
  feature_counter: ^1.0.0
  feature_settings: ^1.0.0
  feature_tmdb: ^1.0.0
  feature_food: ^1.0.0
  feature_wonderous: ^1.0.0
  feature_misc: ^1.0.0
  feature_puzzles: ^1.0.0
  feature_unsplash: ^1.0.0
  feature_conference: ^1.0.0

  # Shared Packages
  design_system: ^1.0.0
  chakra_shared: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/app-icon.png'
  background_color_ios: '#ffffff'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/app-icon.png'
    background_color: '#ffffff'
    theme_color: '#a17fff'

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/launchscreen-image.png'
