name: feature_tmdb
description: A feature_Tmdb feature package for the Vyuh Framework
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  json_annotation: ^4.9.0

  intl: ^0.19.0
  mobx: ^2.3.0+1
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  flutter_mobx: ^2.2.0+2
  flutter_sanity_portable_text: ^1.5.0
  vyuh_core: ^1.25.2
  vyuh_feature_system: ^1.29.1
  vyuh_extension_content: ^1.10.0
  vyuh_cache: ^1.1.0
  photo_view: ^0.15.0
  html: ^0.15.4


  feature_settings: ^1.0.0

  design_system: ^1.0.0
  tmdb_client: ^1.0.0
  chakra_shared: ^1.0.0

  readmore: ^3.0.0
  easy_debounce: ^2.0.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
