name: vyuh_core
description: The core library for the Vyuh framework which contains the base types and runtime.
version: 1.0.0-beta.3
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_core
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  collection: ^1.18.0
  flutter_mobx: ^2.2.0+2
  go_router: ^13.0.1
  json_annotation: ^4.8.1
  mobx: ^2.3.0+1
  get_it: ^7.6.4
  logger: ^2.1.0
  flutter_sanity_portable_text: ^1.0.0-beta.4
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
