name: vyuh_core
description: The core library for the Vyuh framework which contains the base types and runtime.
version: 1.30.2
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_core
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - core
  - system

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cached_network_image: ^3.2.3
  collection: ^1.18.0
  flutter_mobx: ^2.2.0+2
  go_router: ^14.0.1
  json_annotation: ^4.9.0
  mobx: ^2.3.0+1
  get_it: ^8.0.2
  logger: ^2.1.0
  flutter_sanity_portable_text: ^1.5.1
  http: ^1.2.1
  retry: ^3.1.2
  flutter_dotenv: ^5.1.0
  event_bus: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  mocktail: ^1.0.4
  vyuh_test: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
