name: content_explorer
description: A Content Explorer for the Vyuh Demo App, as a Widgetbook. Use this as a reference for your own Vyuh Apps.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # The main package that helps you run the widgetbook
  vyuh_widgetbook: ^1.1.3

  # Shared packages
  design_system: ^1.0.0

  # Vyuh Features
  vyuh_feature_system: ^1.37.0
  vyuh_feature_auth: ^1.16.0
  vyuh_feature_onboarding: ^1.5.0

  # Example Features
  feature_counter: ^1.0.0
  feature_settings: ^1.0.0
  feature_tmdb: ^1.0.0
  feature_food: ^1.0.0
  feature_wonderous: ^1.0.0
  feature_misc: ^1.0.0
  feature_puzzles: ^1.0.0
  feature_unsplash: ^1.0.0
  feature_conference: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
