name: vyuh_plugin_content_provider_sanity
description: A Content Provider for the Vyuh Framework that reads documents from Sanity.io.
version: 1.7.0

homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/sanity/vyuh_plugin_content_provider_sanity
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - plugin
  - content-provider
  - sanity
  - cms

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  sanity_client: ^1.4.0
  vyuh_core: ^1.22.4
  vyuh_cache: ^1.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
